"""Generate Lean 4 theorem files from candidate rule pairs.

Each Candidate becomes a small, self-contained Lean source file that states
both rules as hypotheses and claims their combination is inconsistent
(`False`). Generating the file does NOT verify anything -- see
leanverify.py, which invokes `lake env lean` on each file and only reports a
conflict as confirmed if Lean's kernel actually accepts the proof.

No LLM call happens here; this is template rendering over already-extracted
Rule objects.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from .candidates import Candidate
from .models import Condition, Rule, Statute

_ACTION_TO_LEAN = {"allowed": "Allowed", "prohibited": "Prohibited", "required": "Required"}

_OPERATOR_TO_LEAN = {
    ">=": "≥",
    ">": ">",
    "<=": "≤",
    "<": "<",
    "==": "=",
    "!=": "≠",
}

# (unordered action pair) -> (axiom name, action that must come first, action that must come second)
_EXCLUSION_AXIOMS = {
    frozenset({"allowed", "prohibited"}): ("allowed_prohibited_excl", "allowed", "prohibited"),
    frozenset({"prohibited", "required"}): ("prohibited_required_excl", "prohibited", "required"),
}


def _sanitize(source_id: str) -> str:
    """Turn a statute id like 'az-sb1070-5c' into a Lean-safe identifier fragment."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", source_id)


def _hypothesis_and_proof(rule: Rule, label: str, witness: int) -> tuple[str, str]:
    """Return (hypothesis type as Lean text, proof term instantiating it at `witness`)."""
    action_lean = _ACTION_TO_LEAN[rule.action]
    cond: Condition = rule.condition
    if cond.is_unconditional:
        hyp = f"(∀ x : Int, True → {action_lean} (Activity x))"
        proof = f"{label} {witness} trivial"
    else:
        op = _OPERATOR_TO_LEAN[cond.operator]
        hyp = f"(∀ x : Int, x {op} {cond.value} → {action_lean} (Activity x))"
        proof = f"{label} {witness} (by omega)"
    return hyp, proof


def render_conflict_theorem(candidate: Candidate, statute_a: Statute, statute_b: Statute) -> str:
    a, b = candidate.rule_a, candidate.rule_b
    pair = frozenset({a.action, b.action})
    if pair not in _EXCLUSION_AXIOMS:
        raise ValueError(f"no exclusion axiom for action pair {pair}")
    axiom_name, first_action, second_action = _EXCLUSION_AXIOMS[pair]
    first_rule, second_rule = (a, b) if a.action == first_action else (b, a)

    hyp_a, proof_a = _hypothesis_and_proof(first_rule, "ruleA", candidate.witness)
    hyp_b, proof_b = _hypothesis_and_proof(second_rule, "ruleB", candidate.witness)

    theorem_name = f"conflict_{_sanitize(a.source_id)}_vs_{_sanitize(b.source_id)}"

    return f"""import Legalean.Deontic

/-!
AUTO-GENERATED by src/legalean/leangen.py from data/statutes.json /
data/rules.json -- do not edit by hand, re-run codegen instead.

Source A: {statute_a.citation}
          ({first_rule.scope}) {first_rule.subject}: {first_rule.action} to {first_rule.activity}
Source B: {statute_b.citation}
          ({second_rule.scope}) {second_rule.subject}: {second_rule.action} to {second_rule.activity}

If this file fails to compile, Lean has rejected the claim that these two
rules are jointly inconsistent (e.g. their conditions don't actually
overlap at the chosen witness) -- see leanverify.py, which treats a
compile failure as "not a confirmed conflict", not an error.
-/

private def Activity (_x : Int) : Prop := True

theorem {theorem_name}
    (ruleA : {hyp_a})
    (ruleB : {hyp_b}) :
    False :=
  {axiom_name} (Activity {candidate.witness}) ({proof_a}) ({proof_b})
"""


@dataclass
class GeneratedFile:
    candidate: Candidate
    path: Path
    theorem_name: str


def generate_conflict_files(
    candidates: list[Candidate], statutes_by_id: dict[str, Statute], out_dir: Path
) -> list[GeneratedFile]:
    out_dir.mkdir(parents=True, exist_ok=True)
    for existing in out_dir.glob("*.lean"):
        existing.unlink()

    generated: list[GeneratedFile] = []
    for candidate in candidates:
        statute_a = statutes_by_id[candidate.rule_a.source_id]
        statute_b = statutes_by_id[candidate.rule_b.source_id]
        source = render_conflict_theorem(candidate, statute_a, statute_b)
        theorem_name = f"conflict_{_sanitize(candidate.rule_a.source_id)}_vs_{_sanitize(candidate.rule_b.source_id)}"
        path = out_dir / f"{theorem_name}.lean"
        path.write_text(source, encoding="utf-8")
        generated.append(GeneratedFile(candidate=candidate, path=path, theorem_name=theorem_name))
    return generated
