"""Generate Lean 4 theorem files from candidate rule pairs.

Each Candidate becomes a small, self-contained Lean source file that states
both rules as hypotheses and claims their combination is inconsistent
(`False`). Generating the file does NOT verify anything -- see
leanverify.py, which invokes `lake env lean` on each file and only reports a
conflict as confirmed if Lean's kernel actually accepts the proof.

No LLM call happens here; this is template rendering over already-extracted
Rule objects.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from .candidates import Candidate, Witness
from .models import Condition, Rule, Statute

_ACTION_TO_LEAN = {"allowed": "Allowed", "prohibited": "Prohibited", "required": "Required"}

_OPERATOR_TO_LEAN = {
    ">=": "≥",
    ">": ">",
    "<=": "≤",
    "<": "<",
    "==": "=",
    "!=": "≠",
}

# (unordered action pair) -> (axiom name, action that must come first, action that must come second)
_EXCLUSION_AXIOMS = {
    frozenset({"allowed", "prohibited"}): ("allowed_prohibited_excl", "allowed", "prohibited"),
    frozenset({"prohibited", "required"}): ("prohibited_required_excl", "prohibited", "required"),
}


def _sanitize(source_id: str) -> str:
    """Turn a statute id like 'az-sb1070-5c' into a Lean-safe identifier fragment."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", source_id)


def _lean_literal(value: object) -> str:
    """Render a witness or condition value as Lean source."""
    if isinstance(value, bool):  # must precede int -- bool is an int subclass
        return "true" if value else "false"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, int) and value < 0:
        return f"({value})"  # keep unary minus from binding oddly in application position
    return str(value)


def _hypothesis_and_proof(rule: Rule, label: str, witness: Witness) -> tuple[str, str]:
    """Return (hypothesis type as Lean text, proof term instantiating it at `witness`).

    The premise is discharged by `trivial` when the rule is unconditional,
    `omega` for linear integer arithmetic, and `decide` for Bool/String
    equality -- all three are core Lean, no mathlib.
    """
    action_lean = _ACTION_TO_LEAN[rule.action]
    ty = witness.lean_type
    literal = _lean_literal(witness.value)
    cond: Condition = rule.condition

    if cond.is_unconditional:
        hyp = f"(∀ x : {ty}, True → {action_lean} (Activity x))"
        return hyp, f"{label} {literal} trivial"

    op = _OPERATOR_TO_LEAN[cond.operator]
    hyp = f"(∀ x : {ty}, x {op} {_lean_literal(cond.value)} → {action_lean} (Activity x))"
    tactic = "by omega" if ty == "Int" else "by decide"
    return hyp, f"{label} {literal} ({tactic})"


def render_conflict_theorem(candidate: Candidate, statutes_by_id: dict[str, Statute]) -> str:
    a, b = candidate.rule_a, candidate.rule_b
    pair = frozenset({a.action, b.action})
    if pair not in _EXCLUSION_AXIOMS:
        raise ValueError(f"no exclusion axiom for action pair {pair}")
    axiom_name, first_action, _second_action = _EXCLUSION_AXIOMS[pair]
    # The exclusion axiom fixes the order of its two proof arguments, which
    # need not match the candidate's own order -- so resolve each citation
    # from the rule it actually describes, never from candidate order.
    first_rule, second_rule = (a, b) if a.action == first_action else (b, a)
    first_statute = statutes_by_id[first_rule.source_id]
    second_statute = statutes_by_id[second_rule.source_id]

    hyp_a, proof_a = _hypothesis_and_proof(first_rule, "ruleA", candidate.witness)
    hyp_b, proof_b = _hypothesis_and_proof(second_rule, "ruleB", candidate.witness)

    # Both rules quantify over the same carrier type, fixed by the witness.
    ty = candidate.witness.lean_type
    witness_literal = _lean_literal(candidate.witness.value)

    theorem_name = f"conflict_{_sanitize(a.source_id)}_vs_{_sanitize(b.source_id)}"

    return f"""import Legalean.Deontic

/-!
AUTO-GENERATED by src/legalean/leangen.py from the markdown corpus in
statutes/ -- do not edit by hand, re-run codegen instead.

ruleA: {first_statute.citation}
       ({first_rule.scope}) {first_rule.subject}: {first_rule.action} to {first_rule.activity}
ruleB: {second_statute.citation}
       ({second_rule.scope}) {second_rule.subject}: {second_rule.action} to {second_rule.activity}

If this file fails to compile, Lean has rejected the claim that these two
rules are jointly inconsistent (e.g. their conditions don't actually
overlap at the chosen witness) -- see leanverify.py, which treats a
compile failure as "not a confirmed conflict", not an error.
-/

private def Activity (_x : {ty}) : Prop := True

theorem {theorem_name}
    (ruleA : {hyp_a})
    (ruleB : {hyp_b}) :
    False :=
  {axiom_name} (Activity {witness_literal}) ({proof_a}) ({proof_b})
"""


@dataclass
class GeneratedFile:
    candidate: Candidate
    path: Path
    theorem_name: str


def generate_conflict_files(
    candidates: list[Candidate], statutes_by_id: dict[str, Statute], out_dir: Path
) -> list[GeneratedFile]:
    out_dir.mkdir(parents=True, exist_ok=True)
    for existing in out_dir.glob("*.lean"):
        existing.unlink()

    generated: list[GeneratedFile] = []
    for candidate in candidates:
        source = render_conflict_theorem(candidate, statutes_by_id)
        theorem_name = f"conflict_{_sanitize(candidate.rule_a.source_id)}_vs_{_sanitize(candidate.rule_b.source_id)}"
        path = out_dir / f"{theorem_name}.lean"
        path.write_text(source, encoding="utf-8")
        generated.append(GeneratedFile(candidate=candidate, path=path, theorem_name=theorem_name))
    return generated
